---
ldk_monitoring_base_dir: /opt/ldk/monitoring
ldk_promtail_image: grafana/promtail:2.9.8
ldk_promtail_loki_url: https://loki.monitoring.invalid/loki/api/v1/push
ldk_promtail_job_name: laravel
ldk_promtail_log_path: /var/log/*.log
ldk_monitoring_restart_policy: unless-stopped

