---
extends: default

rules:
  line-length:
    max: 140
    level: warning
  truthy:
    allowed-values: ["true", "false", "on", "off"]
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  document-start: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

ignore: |
  .git/
  **/__pycache__/
  ansible/roles/*/templates/*.j2
