services:
  promtail:
    image: grafana/promtail:3.0.0
    command: -config.file=/etc/promtail/config.yml
    environment:
      LOKI_USERNAME: ${LOKI_USERNAME:-fake-user}
      LOKI_PASSWORD: ${LOKI_PASSWORD:-fake-password}
    volumes:
      - ./deploy/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped

